import 'package:fitaicoatch_app/l10n/app_localizations.dart';

class ProgramGenerator {
  Map<String, List<Map<String, String>>> generateProgram({
    required String goal,
    required double weight,
    required double height,
    required String gender,
    required AppLocalizations t,
  }) {
    /// 🔴 FEMALE PRO
    if (gender.toLowerCase().trim() == 'female') {
      return {
        t.day1: [
          {
            'exercise': t.hipThrust,
            'sets': '4',
            'reps': '12',
            'description': t.hipThrustDesc,
            'video': 'https://www.youtube.com/watch?v=example1',
            'imageStart': 'images/hip_thrust_begin.jpg',
            'imageEnd': 'images/hip_thrust_end.jpg',
          },
          {
            'exercise': t.gluteBridge,
            'sets': '3',
            'reps': '15',
            'description': t.gluteBridgeDesc,
            'video': 'https://www.youtube.com/watch?v=example2',
            'imageStart': 'images/glute_bridge_begin.jpg',
            'imageEnd': 'images/glute_bridge_end.jpg',
          },
          {
            'exercise': t.cableKickbacks,
            'sets': '3',
            'reps': '12 each',
            'description': t.cableKickbacksDesc,
            'video': 'https://www.youtube.com/watch?v=example3',
            'imageStart': 'images/cable_kickbacks_begin.jpg',
            'imageEnd': 'images/cable_kickbacks_end.jpg',
          },
          {
            'exercise': t.bulgarianSplitSquat,
            'sets': '3',
            'reps': '12 each',
            'description': t.bulgarianSplitSquatDesc,
            'video': 'https://www.youtube.com/watch?v=example4',
            'imageStart': 'images/bulgarian_split_begin.jpg',
            'imageEnd': 'images/bulgarian_split_end.jpg',
          },
          {
            'exercise': t.stepUps,
            'sets': '3',
            'reps': '12 each',
            'description': t.stepUpsDesc,
            'video': 'https://www.youtube.com/watch?v=example5',
            'imageStart': 'images/step_ups_begin.jpg',
            'imageEnd': 'images/step_ups_end.jpg',
          },
          {
            'exercise': t.abductionMachine,
            'sets': '3',
            'reps': '15',
            'description': t.abductionMachineDesc,
            'video': 'https://www.youtube.com/watch?v=example6',
            'imageStart': 'images/abduction_machine_begin.jpg',
            'imageEnd': 'images/abduction_machine_end.jpg',
          },
        ],
        t.day2: [
          {
            'exercise': t.latPulldown,
            'sets': '4',
            'reps': '10-12',
            'description': t.latPulldownDesc,
            'video': 'https://www.youtube.com/watch?v=example7',
            'imageStart': 'images/lat_pulldown_begin.jpg',
            'imageEnd': 'images/lat_pulldown_end.jpg',
          },
          {
            'exercise': t.dumbbellRow,
            'sets': '4',
            'reps': '10-12',
            'description': t.dumbbellRowDesc,
            'video': 'https://www.youtube.com/watch?v=example8',
            'imageStart': 'images/dumbbell_row_begin.jpg',
            'imageEnd': 'images/dumbbell_row_end.jpg',
          },
          {
            'exercise': t.shoulderPress,
            'sets': '3',
            'reps': '12',
            'description': t.dumbbellRowDesc,
            'video': 'https://www.youtube.com/watch?v=example9',
            'imageStart': 'images/shoulder_press_begin.jpg',
            'imageEnd': 'images/shoulder_press_end.jpg',
          },
          {
            'exercise': t.lateralRaise,
            'sets': '3',
            'reps': '12-15',
            'description': t.lateralRaiseDesc,
            'video': 'https://www.youtube.com/watch?v=example10',
            'imageStart': 'images/lateral_raise_begin.jpg',
            'imageEnd': 'images/lateral_raise_end.jpg',
          },
          {
            'exercise': t.tricepPushdown,
            'sets': '3',
            'reps': '12',
            'description': t.tricepPushdownDesc,
            'video': 'https://www.youtube.com/watch?v=example11',
            'imageStart': 'images/tricep_pushdown_begin.jpg',
            'imageEnd': 'images/tricep_pushdown_end.jpg',
          },
          {
            'exercise': t.bicepCurl,
            'sets': '3',
            'reps': '12',
            'description': t.bicepCurlDesc,
            'video': 'https://www.youtube.com/watch?v=example12',
            'imageStart': 'images/bicep_curl_begin.jpg',
            'imageEnd': 'images/bicep_curl_end.jpg',
          },
        ],
        t.day3: [
          {
            'exercise': t.squats,
            'sets': '4',
            'reps': '10-12',
            'description': t.squatsDesc,
            'video': 'https://www.youtube.com/watch?v=example13',
            'imageStart': 'images/squats_begin.jpg',
            'imageEnd': 'images/squats_end.jpg',
          },
          {
            'exercise': t.legPress,
            'sets': '4',
            'reps': '12',
            'description': t.legPressDesc,
            'video': 'https://www.youtube.com/watch?v=example14',
            'imageStart': 'images/leg_press_begin.jpg',
            'imageEnd': 'images/leg_press_end.jpg',
          },
          {
            'exercise': t.romanianDeadlift,
            'sets': '3',
            'reps': '10-12',
            'description': t.romanianDeadlift,
            'video': 'https://www.youtube.com/watch?v=example15',
            'imageStart': 'images/romanian_deadlift_begin.jpg',
            'imageEnd': 'images/romanian_deadlift_end.jpg',
          },
          {
            'exercise': t.legCurl,
            'sets': '3',
            'reps': '12-15',
            'description': t.legCurlDesc,
            'video': 'https://www.youtube.com/watch?v=example16',
            'imageStart': 'images/leg_curl_begin.jpg',
            'imageEnd': 'images/leg_curl_end.jpg',
          },
          {
            'exercise': t.legExtension,
            'sets': '3',
            'reps': '12',
            'description': t.legExtensionDesc,
            'video': 'https://www.youtube.com/watch?v=example17',
            'imageStart': 'images/leg_extension_begin.jpg',
            'imageEnd': 'images/leg_extension_end.jpg',
          },
          {
            'exercise': t.calfRaises,
            'sets': '4',
            'reps': '15-20',
            'description': t.calfRaisesDesc,
            'video': 'https://www.youtube.com/watch?v=example18',
            'imageStart': 'images/calf_raises_begin.jpg',
            'imageEnd': 'images/calf_raises_end.jpg',
          },
        ],
        t.day4: [
          {
            'exercise': t.plank,
            'sets': '3',
            'reps': '60 sec',
            'description': t.plankDesc,
            'video': 'https://www.youtube.com/watch?v=example19',
            'imageStart': 'images/plank_begin.jpg',
            'imageEnd': 'images/plank_end.jpg',
          },
          {
            'exercise': t.russianTwists,
            'sets': '3',
            'reps': '20',
            'description': t.russianTwistsDesc,
            'video': 'https://www.youtube.com/watch?v=example20',
            'imageStart': 'images/russian_twist_begin.jpg',
            'imageEnd': 'images/russian_twist_end.jpg',
          },
          {
            'exercise': t.mountainClimbers,
            'sets': '3',
            'reps': '30 sec',
            'description': t.mountainClimbersDesc,
            'video': 'https://www.youtube.com/watch?v=example21',
            'imageStart': 'images/mountain_climbers_begin.jpg',
            'imageEnd': 'images/mountain_climbers_end.jpg',
          },
          {
            'exercise': t.jumpRope,
            'sets': '3',
            'reps': '1 min',
            'description': t.jumpRopeDesc,
            'video': 'https://www.youtube.com/watch?v=example22',
            'imageStart': 'images/jump_rope_begin.jpg',
            'imageEnd': 'images/jump_rope_end.jpg',
          },
          {
            'exercise': t.treadmill,
            'sets': '1',
            'reps': '30 min',
            'description': t.treadmillDesc,
            'video': 'https://www.youtube.com/watch?v=example23',
            'imageStart': 'images/treadmill_begin.jpg',
            'imageEnd': 'images/treadmill_end.jpg',
          },
        ],
        t.day5: [
          {
            'exercise': t.walking,
            'sets': '1',
            'reps': '20 min',
            'description': t.walkingDesc,
            'video': 'https://www.youtube.com/watch?v=example24',
            'imageStart': 'images/walking_begin.jpg',
            'imageEnd': 'images/walking_end.jpg',
          },
          {
            'exercise': t.stretching,
            'sets': '-',
            'reps': '-',
            'description': t.stretchingDesc,
            'video': '',
            'imageStart': 'images/stretching_begin.jpg',
            'imageEnd': 'images/stretching_end.jpg',
          },
          {
            'exercise': t.yoga,
            'sets': '-',
            'reps': '-',
            'description': t.yogaDesc,
            'video': '',
            'imageStart': 'images/yoga_begin.jpg',
            'imageEnd': 'images/yoga_end.jpg',
          },
        ],
      };
    }

    /// 🔵 MALE PRO (Bulking/Cutting/Fitness)
    final maleProgram = {
      t.day1: [
        {
          'exercise': t.benchPress,
          'sets': '4',
          'reps': '8-10',
          'description': t.benchPressDesc,
          'video': 'https://www.youtube.com/watch?v=gRVjAtPip0Y',
          'imageStart': 'images/hbench_press_begin.jpg',
          'imageEnd': 'images/hbench_press_end.jpg',
        },
        {
          'exercise': t.inclineDumbbellPress,
          'sets': '4',
          'reps': '8-12',
          'description': t.inclineDumbbellPressDesc,
          'video': 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
          'imageStart': 'images/hicline_dumbbell_press_begin.jpg',
          'imageEnd': 'images/hicline_dumbbell_press_end.jpg',
        },
        {
          'exercise': t.chestFly,
          'sets': '3',
          'reps': '10-12',
          'description': t.chestFlyDesc,
          'video': 'https://www.youtube.com/watch?v=eozdVDA78K0',
          'imageStart': 'images/hchest_fly_begin.jpg',
          'imageEnd': 'images/hchest_fly_end.jpg',
        },
        {
          'exercise': t.cableCrossover,
          'sets': '3',
          'reps': '12',
          'description': t.cableCrossoverDesc,
          'video': 'https://www.youtube.com/watch?v=E3xG7g3KGjE',
          'imageStart': 'images/hcable_crossover_begin.jpg',
          'imageEnd': 'images/hcable_crossover_end.jpg',
        },
        {
          'exercise': t.pushUps,
          'sets': '3',
          'reps': 'max',
          'description': t.pushUpsDesc,
          'video': 'https://www.youtube.com/watch?v=_l3ySVKYVJ8',
          'imageStart': 'images/hpushups_begin.jpg',
          'imageEnd': 'images/hpushups_end.jpg',
        },
        {
          'exercise': t.dips,
          'sets': '3',
          'reps': '12',
          'description': t.dipsDesc,
          'video': 'https://www.youtube.com/watch?v=2z8JmcrW-As',

          'imageStart': 'images/hdips_begin.jpg',
          'imageEnd': 'images/hdips_end.jpg',
        },
      ],
      t.day2: [
        {
          'exercise': t.pullUps,
          'sets': '4',
          'reps': '8-10',
          'description': t.pullUpsDesc,
          'video': 'https://www.youtube.com/watch?v=eGo4IYlbE5g',
          'imageStart': 'images/hpullups_begin.jpg',
          'imageEnd': 'images/hpullups_end.jpg',
        },
        {
          'exercise': t.barbellRow,
          'sets': '4',
          'reps': '8-10',
          'description': t.barbellRowDesc,
          'video': 'https://www.youtube.com/watch?v=vT2GjY_Umpw',
          'imageStart': 'images/hbarbell_row_begin.jpg',
          'imageEnd': 'images/hbarbell_row_end.jpg',
        },
        {
          'exercise': t.latPulldown,
          'sets': '3',
          'reps': '10-12',
          'description': t.latPulldownDesc,
          'video': 'https://www.youtube.com/watch?v=CAwf7n6Luuc',
          'imageStart': 'images/hlat_pulldown_begin.jpg',
          'imageEnd': 'images/hlat_pulldown_end.jpg',
        },
        {
          'exercise': t.seatedRow,
          'sets': '3',
          'reps': '10-12',
          'description': t.seatedRowDesc,
          'video': 'https://www.youtube.com/watch?v=GZbfZ033f74',
          'imageStart': 'images/hseated_row_begin.jpg',
          'imageEnd': 'images/hseated_row_end.jpg',
        },
        {
          'exercise': t.facePull,
          'sets': '3',
          'reps': '15',
          'description': t.facePullDesc,
          'video': 'https://www.youtube.com/watch?v=rep-qVOkqgk',
          'imageStart': 'images/hface_pull_begin.jpg',
          'imageEnd': 'images/hface_pull_end.jpg',
        },
        {
          'exercise': t.deadlift,
          'sets': '3',
          'reps': '5',
          'description': t.deadliftDesc,
          'video': 'https://www.youtube.com/watch?v=r4MzxtBKyNE',
          'imageStart': 'images/hdeadlift_begin.jpg',
          'imageEnd': 'images/hdeadlift_end.jpg',
        },
      ],
      t.day3: [
        // Legs
        {
          'exercise': t.squats,
          'sets': '4',
          'reps': '8-10',
          'description': t.squatsDesc,
          'video': 'https://www.youtube.com/watch?v=aclHkVaku9U',
          'imageStart': 'images/hsquats_begin.jpg',
          'imageEnd': 'images/hsquats_end.jpg',
        },
        {
          'exercise': t.legPress,
          'sets': '4',
          'reps': '10-12',
          'description': t.legPressDesc,
          'video': 'https://www.youtube.com/watch?v=IZxyjW7MPJQ',
          'imageStart': 'images/hleg_press_begin.jpg',
          'imageEnd': 'images/hleg_press_end.jpg',
        },
        {
          'exercise': t.lunges,
          'sets': '3',
          'reps': '12 each',
          'description': t.lungesDesc,
          'video': 'https://www.youtube.com/watch?v=QOVaHwm-Q6U',
          'imageStart': 'images/hlunges_begin.jpg',
          'imageEnd': 'images/hlunges_end.jpg',
        },
        {
          'exercise': t.legCurl,
          'sets': '3',
          'reps': '12-15',
          'description': t.legCurlDesc,
          'video': 'https://www.youtube.com/watch?v=PY2u0gqew2I',
          'imageStart': 'images/hleg_curl_begin.jpg',
          'imageEnd': 'images/hleg_curl_end.jpg',
        },
        {
          'exercise': t.legExtension,
          'sets': '3',
          'reps': '12',
          'description': t.legExtensionDesc,
          'video': 'https://www.youtube.com/watch?v=YyvSfVjQeL0',
          'imageStart': 'images/hleg_extension_begin.jpg',
          'imageEnd': 'images/hleg_extension_end.jpg',
        },
        {
          'exercise': t.calfRaises,
          'sets': '5',
          'reps': '20',
          'description': t.calfRaisesDesc,
          'video': 'https://www.youtube.com/watch?v=YMmgqO8Jo-k',
          'imageStart': 'images/hcalf_raises_begin.jpg',
          'imageEnd': 'images/hcalf_raises_end.jpg',
        },
      ],
      t.day4: [
        {
          'exercise': t.shoulderPress,
          'sets': '4',
          'reps': '8-10',
          'description': t.shoulderPressDesc,
          'video': 'https://www.youtube.com/watch?v=B-aVuyhvLHU',
          'imageStart': 'images/hshoulder_press_begin.jpg',
          'imageEnd': 'images/hshoulder_press_end.jpg',
        },
        {
          'exercise': t.lateralRaise,
          'sets': '4',
          'reps': '12',
          'description': t.lateralRaiseDesc,
          'video': 'https://www.youtube.com/watch?v=kDqklk1ZESo',
          'imageStart': 'images/hlateral_raise_begin.jpg',
          'imageEnd': 'images/hlateral_raise_end.jpg',
        },
        {
          'exercise': t.frontRaise,
          'sets': '3',
          'reps': '12',
          'description': t.frontRaiseDesc,
          'video': 'https://www.youtube.com/watch?v=-t7fuZ0KhDA',
          'imageStart': 'images/hfront_raise_begin.jpg',
          'imageEnd': 'images/hfront_raise_end.jpg',
        },
        {
          'exercise': t.reverseFly,
          'sets': '3',
          'reps': '12',
          'description': t.reverseFlyDesc,
          'video': 'https://www.youtube.com/watch?v=5v32Wv4cgrk',
          'imageStart': 'images/hreverse_fly_begin.jpg',
          'imageEnd': 'images/hreverse_fly_end.jpg',
        },
        {
          'exercise': t.shrugs,
          'sets': '4',
          'reps': '15',
          'description': t.shrugsDesc,
          'video': 'https://www.youtube.com/watch?v=0qj4WTmxmAU',
          'imageStart': 'images/hshrugs_begin.jpg',
          'imageEnd': 'images/hshrugs_end.jpg',
        },
      ],
      t.day5: [
        {
          'exercise': t.barbellCurl,
          'sets': '4',
          'reps': '10',
          'description': t.barbellCurlDesc,
          'video': 'https://www.youtube.com/watch?v=kwG2ipFRgfo',
          'imageStart': 'images/hbarbell_curl_begin.jpg',
          'imageEnd': 'images/hbarbell_curl_end.jpg',
        },
        {
          'exercise': t.hammerCurl,
          'sets': '3',
          'reps': '12',
          'description': t.hammerCurlDesc,
          'video': 'https://www.youtube.com/watch?v=zC3nLlEvin4',
          'imageStart': 'images/hhammer_curl_begin.jpg',
          'imageEnd': 'images/hhammer_curl_end.jpg',
        },
        {
          'exercise': t.tricepPushdown,
          'sets': '4',
          'reps': '12',
          'description': t.tricepPushdownDesc,
          'video': 'https://www.youtube.com/watch?v=2-LAMcpzODU',
          'imageStart': 'images/htricep_pushdown_begin.jpg',
          'imageEnd': 'images/htricep_pushdown_end.jpg',
        },
        {
          'exercise': t.skullCrushers,
          'sets': '3',
          'reps': '10',
          'description': t.skullCrushersDesc,
          'video': 'https://www.youtube.com/watch?v=d_KZxkY_0cM',
          'imageStart': 'images/hskull_crushers_begin.jpg',
          'imageEnd': 'images/hskull_crushers_end.jpg',
        },
        {
          'exercise': t.dips,
          'sets': '3',
          'reps': 'max',
          'description': t.dipsDesc,
          'video': 'https://www.youtube.com/watch?v=2z8JmcrW-As',
          'imageStart': 'images/hdips_begin.jpg',
          'imageEnd': 'images/hdips_end.jpg',
        },
      ],
    };

    /// ✅ Adjust program by goal
    if (goal == 'Bulking') {
      return maleProgram;
    } else if (goal == 'Cutting') {
      // Example cutting adjustments
      maleProgram[t.day1] = [
        {
          'exercise': t.treadmill,
          'sets': '1',
          'reps': '30 min',
          'description': t.treadmillDesc,
          'video': 'https://www.youtube.com/watch?v=example_cut1',
          'imageStart': 'images/treadmill_begin.jpg',
          'imageEnd': 'images/treadmill_end.jpg',
        },
        {
          'exercise': t.jumpRope,
          'sets': '3',
          'reps': '1 min',
          'description': t.jumpRopeDesc,
          'video': 'https://www.youtube.com/watch?v=example_cut2',
          'imageStart': 'images/jump_rope_begin.jpg',
          'imageEnd': 'images/jump_rope_end.jpg',
        },
      ];
      maleProgram[t.day4] = [
        {
          'exercise': t.fullBodyCircuit,
          'sets': '4',
          'reps': '12 each',
          'description': t.fullBodyCircuitDesc,
          'video': 'https://www.youtube.com/watch?v=example_cut3',
          'imageStart': 'images/full_body_circuit_begin.jpg',
          'imageEnd': 'images/full_body_circuit_end.jpg',
        },
      ];
      return maleProgram;
    } else {
      // Fitness / Maintenance
      return maleProgram;
    }
  }
}
